### ISSUE TITLE
BOTA UNS PRINT AI NESSE README

### ISSUE THREAD

**Issue by luanbitar** [Nhanderu/dois-mil#1]
TO AFIM DE INSTALAR NAO SO QUERO VER COMO TA, VALEU MT BOM PARABENS

**Comment by luanbitar** [comment]
GIF GIF, MELHOR BOTAR GIF, BOTA LA PO, VAI FICAR LEGAL PO

**Comment by Nhanderu** [comment]
Tá tudo bem aí, irmão?

**Comment by Nhanderu** [comment]
Tem um asciinema bonitinho agora.
